services:
  openwrt:
    image: 14790897/openwrt:x86_64
    container_name: openwrt
    restart: always
    privileged: true
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.188 # 为容器指定静态 IP 地址
    command: /sbin/init

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: 192.168.0.0/24 # 定义容器使用的子网
          gateway: 192.168.0.1 # 定义网关
# ip link add macvlan0 link enp1s0 type macvlan mode bridge # 注意重启后不保留
# ip addr add 192.168.0.198/24 dev macvlan0  # 分配在与容器相同子网内的 IP
# ip link set macvlan0 up
# ip route add 192.168.0.188 dev macvlan0
# 使用这个不需要开启网卡混杂模式 ip link set dev enp1s0 promisc on
